### ISSUE TITLE
User Actions

### ISSUE THREAD

**Issue by uwojeyamudiaga** [chingu-voyages/v39-bears-team-11#120]
**__Feature Description__**
The user actions is the combination of features to allow a user add and remove a friend, delete and update their profile.

**__Major User Stories/tasks__**
- [ ] As a user, I want to be able to add new friends to my list
- [ ] As a user, I want to be able to remove friends from my list
- [ ] As a user, I want to be able to update my profile
- [ ] As a user, I want to be able to delete my profile

**__Additional Considerations__**
These actions will be created in the `user slice` using `redux` library.
