### ISSUE TITLE
Initialise the project

### ISSUE THREAD

**Issue by jaceksupernak** [chingu-voyages/v39-bears-team-11#19]
**__Feature Description__**
Describe what the feature is intended to accomplish & why it's important

**__Major User Stories/tasks__**
- [ ] Create React App 
- [ ] Initialise Nodejs App 
- [ ] Initialise Golang App?
- [ ] Install the dependencies required for the project
- [ ] Create the folder structure

**__Additional Considerations__**
Include anything else that may be helpful. For example, links to external resources.
