### ISSUE TITLE
Deploy project

### ISSUE THREAD

**Issue by jaceksupernak** [chingu-voyages/v39-bears-team-11#20]
**__Feature Description__**
Deploy the project

**__Major User Stories/tasks__**
- [ ] Create heroku account for the team
- [ ] Create heroku configuration 
- [ ] Deploy the project to heroku
- [ ] Get the live link of the application

**__Additional Considerations__**
Include anything else that may be helpful. For example, links to external resources.
