### ISSUE TITLE
Initialize the databse

### ISSUE THREAD

**Issue by jaceksupernak** [chingu-voyages/v39-bears-team-11#21]
**__Feature Description__**
Describe what the feature is intended to accomplish & why it's important

**__Major User Stories/tasks__**
- [ ] Create MongoDb Atlas account
- [ ] Configure MongoDb Atlas account
- [ ] Define database schemas
- [ ] Get the MongoDb URI

**__Additional Considerations__**
Include anything else that may be helpful. For example, links to external resources.
