### ISSUE TITLE
Implement Pages

### ISSUE THREAD

**Issue by jaceksupernak** [chingu-voyages/v39-bears-team-11#82]
**__Feature Description__**
Implement all the pages from design into HTML/CSS so they are ready to have the functionalities built on top of them.

**__Major User Stories/tasks__**
- [ ] Signup and Login Page Implementation
- [ ] Main Page Implementation
- [ ] Contacts Page Implementation
- [ ] Last Messages Page Implementation
- [ ] Profile Page Implementation
- [ ] Chat Page Implementation

**__Additional Considerations__**
Include anything else that may be helpful. For example, links to external resources.
