### ISSUE TITLE
Implement Sign Up Form component

### ISSUE THREAD

**Issue by jaceksupernak** [chingu-voyages/v39-bears-team-11#87]
**__Task Description__**
Implement Sign Up Form component. Turn the design into code.
- [x] Create SignUp.js file inside the components folder
- [x] Create signup.module.css CSS file inside the styles folder
- [x] Create HTML structure
- [x] Create CSS styling

<br/>

**__Additional Resources__**

[The Figma Design Link](https://www.figma.com/file/vh5P0J7NNAjHwJB4t69weF/Litetalk_Signup-Profile-Chats?node-id=56%3A20)

**__Pictures__**
![Screen Shot 2022-04-20 at 00 24 19](https://user-images.githubusercontent.com/66032213/164117128-aa1c2462-efc2-4d8d-87f9-115430589ecc.png)
![Screen Shot 2022-04-20 at 00 24 23](https://user-images.githubusercontent.com/66032213/164117136-4b7f09bd-f80a-40d8-a527-709fd0ea615f.png)
